---
name: danger

on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Danger
        uses: actionshub/danger-rb@fix
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# hello world
